name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    - cron: 0 0 * * * echo "Nightly system check executed" >> /home/deploy/system_check.log
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

  
